/* EasyCODE V8 */
/* EasyCODE ( 0 */
//****************************************************************************
// @Module        Main
// @Filename      MAINBS3.H
// @Project       Bs3
//----------------------------------------------------------------------------
// @Controller    Siemens C167CR-L
//
// @Compiler      Keil C166 V3.00
//
// @Codegenerator DAvE 1-0-0
//
// @Description   This is the include header file for all other modules.
//
//----------------------------------------------------------------------------
// @Date          07.04.98 13:59:53
//
//****************************************************************************

//****************************************************************************
// @Defines
//****************************************************************************

#define ulong unsigned long
#define uword unsigned int
#define ubyte unsigned char

#define KEIL


// USER CODE BEGIN (MainHeader,0)

// USER CODE END

//****************************************************************************
// @Project Includes
//****************************************************************************

#include <reg167.h>
#include <intrins.h>
#include <math.h>       // portal wegen abs funktion

#include "IO.H"
#include "ASC.H"
#include "CANBS3.H"
#include "PWM.H"
#include "CC1.H"
#include "CC2.H"
#include "GT1.H"
#include "GT2.H"
#include "INT.H"

// USER CODE BEGIN (MainHeader,1)

// USER CODE END
/* EasyCODE ) */
