//****************************************************************************
// @Module        Main
// @Filename      MAIN.H
// @Project       Bs3
//----------------------------------------------------------------------------
// @Controller    Siemens C167CR-L
//
// @Compiler      Keil C166 V3.00
//
// @Codegenerator DAvE 1-0-0
//
// @Description   This is the include header file for all other modules.
//
//----------------------------------------------------------------------------
// @Date          18.09.98 10:00:58
//
//****************************************************************************

//****************************************************************************
// @Defines
//****************************************************************************

#define ulong unsigned long
#define uword unsigned int
#define ubyte unsigned char

#define KEIL


// USER CODE BEGIN (MainHeader,0)

// USER CODE END

//****************************************************************************
// @Project Includes
//****************************************************************************

#include <reg167.h>
#include <intrins.h>

#include "IO.H"
#include "ASC.H"
#include "CAN.H"
#include "PWM.H"
#include "CC1.H"
#include "CC2.H"
#include "GT1.H"
#include "GT2.H"
#include "INT.H"

// USER CODE BEGIN (MainHeader,1)

// USER CODE END

